# Generated by Django 2.2 on 2020-01-16 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0004_auto_20200116_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
