# Generated by Django 2.2 on 2020-01-16 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0005_auto_20200116_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
