# Generated by Django 2.2 on 2020-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0006_auto_20200116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
