# Generated by Django 2.2 on 2020-01-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default='San Jose', max_length=255),
            preserve_default=False,
        ),
    ]
