# Generated by Django 2.2 on 2020-01-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
    ]
