# Generated by Django 2.2 on 2020-01-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Dojos'),
            preserve_default=False,
        ),
    ]
