# Generated by Django 2.2 on 2020-01-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyToMany_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='note',
            field=models.TextField(default='Notes on my Books'),
            preserve_default=False,
        ),
    ]
